# Generated by Django 2.2.3 on 2019-07-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendaftaranMember',
            fields=[
                ('id_anggota', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('nama_lengkap', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('password_repeat', models.CharField(max_length=10)),
                ('tgl_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.CharField(max_length=50)),
                ('no_hp', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('id_instagram', models.CharField(max_length=50)),
                ('fb_url', models.CharField(max_length=50)),
                ('web_portofolio_url', models.CharField(max_length=50)),
                ('pekerjaan', models.CharField(choices=[('pljr/mhs', 'Pelajar/Mahasiswa'), ('freelance', 'Freelance'), ('karyawan', 'Karyawan'), ('blmbekerja', 'Belum Bekerja'), ('tgahli', 'Tenaga Ahli'), ('wiraswasta', 'Wiraswasta'), (' ', 'Yang lain:')], max_length=15)),
                ('bidang_desain', models.CharField(max_length=150)),
                ('program_desain', models.CharField(max_length=150)),
                ('deskripsi_diri', models.CharField(max_length=500)),
                ('tujuan_gabung_bogrades', models.CharField(max_length=500)),
                ('harapan_gabung_bogrades', models.CharField(max_length=500)),
                ('upload_foto_diri', models.FilePathField(path='/img')),
                ('upload_portofolio', models.FilePathField(path='/portofolio')),
            ],
        ),
    ]
