# Generated by Django 2.2.3 on 2019-07-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdata',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='bidang_desain',
            field=models.CharField(choices=[('branding', 'Branding'), ('illustration', 'Illustration'), ('publication', 'Publication'), ('webdesign', 'Web Design'), ('photography', 'Photography'), ('infographic', 'Infographic'), ('mograph', 'Motion Graphic'), ('dgimaging', 'Digital Imaging'), ('typography', 'Typography'), ('wpap', 'WPAP'), ('lettering', 'Lettering'), ('doodle', 'Doodle'), ('mural', 'Mural'), ('drawing', 'drawing'), ('fashiondesign', 'Fashion Design'), ('lain', 'Lain-lain')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='deskripsi_diri',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='fb_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='harapan_gabung_bogrades',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='id_instagram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='pekerjaan',
            field=models.CharField(choices=[('pljr/mhs', 'Pelajar/Mahasiswa'), ('freelance', 'Freelance'), ('karyawan', 'Karyawan'), ('blmbekerja', 'Belum Bekerja'), ('tgahli', 'Tenaga Ahli'), ('wiraswasta', 'Wiraswasta'), ('lain', 'Lain-lain')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='program_desain',
            field=models.CharField(choices=[('manual', 'Manual'), ('ps', 'Adobe Photoshop'), ('ai', 'Adobe Illustrator'), ('id', 'Adobe Indesign'), ('corel', 'CorelDraw'), ('autocad', 'Autocad'), ('paint', 'Paint'), ('mangastudio', 'Manga Studio'), ('quark', 'Quark Xpress'), ('3ds', '3D Max'), ('ink', 'Inkscape'), ('sketchup', 'Google SketchUp'), ('macromedia', 'Macromedia Freehand'), ('lain', 'Lain-lain')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='tgl_lahir',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='tujuan_gabung_bogrades',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='upload_foto_diri',
            field=models.ImageField(null=True, upload_to='photoprofile/'),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='upload_portofolio',
            field=models.ImageField(null=True, upload_to='portofolio/'),
        ),
        migrations.AddField(
            model_name='accountdata',
            name='web_portofolio_url',
            field=models.URLField(null=True),
        ),
    ]
