# Generated by Django 2.2.3 on 2019-08-05 01:47

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('tgl_lahir', models.DateField(null=True, verbose_name='Tanggal Lahir')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True)),
                ('alamat', models.TextField(null=True)),
                ('no_handphone', models.CharField(max_length=30)),
                ('id_instagram', models.CharField(max_length=50, null=True)),
                ('fb_url', models.URLField(null=True)),
                ('web_portofolio_url', models.URLField(null=True)),
                ('pekerjaan', models.CharField(choices=[('pljr/mhs', 'Pelajar/Mahasiswa'), ('freelance', 'Freelance'), ('karyawan', 'Karyawan'), ('blmbekerja', 'Belum Bekerja'), ('tgahli', 'Tenaga Ahli'), ('wiraswasta', 'Wiraswasta'), ('lain', 'Lain-lain')], max_length=15, null=True)),
                ('bidang_desain', models.CharField(choices=[('branding', 'Branding'), ('illustration', 'Illustration'), ('publication', 'Publication'), ('webdesign', 'Web Design'), ('photography', 'Photography'), ('infographic', 'Infographic'), ('mograph', 'Motion Graphic'), ('dgimaging', 'Digital Imaging'), ('typography', 'Typography'), ('wpap', 'WPAP'), ('lettering', 'Lettering'), ('doodle', 'Doodle'), ('mural', 'Mural'), ('drawing', 'drawing'), ('fashiondesign', 'Fashion Design'), ('lain', 'Lain-lain')], max_length=15, null=True)),
                ('program_desain', models.CharField(choices=[('manual', 'Manual'), ('ps', 'Adobe Photoshop'), ('ai', 'Adobe Illustrator'), ('id', 'Adobe Indesign'), ('corel', 'CorelDraw'), ('autocad', 'Autocad'), ('paint', 'Paint'), ('mangastudio', 'Manga Studio'), ('quark', 'Quark Xpress'), ('3ds', '3D Max'), ('ink', 'Inkscape'), ('sketchup', 'Google SketchUp'), ('macromedia', 'Macromedia Freehand'), ('lain', 'Lain-lain')], max_length=15, null=True)),
                ('deskripsi_diri', models.TextField(null=True)),
                ('tujuan_gabung_bogrades', models.TextField(null=True)),
                ('harapan_gabung_bogrades', models.TextField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
