# Generated by Django 2.2.3 on 2019-07-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_imageprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofile',
            name='profileimage',
            field=models.ImageField(upload_to='photoprofile/'),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='image',
            field=models.ImageField(upload_to='portofolio/'),
        ),
    ]
