# Generated by Django 2.2.3 on 2019-08-06 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190723_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portofolio',
            name='image',
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portofolio/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.Portofolio')),
            ],
        ),
    ]
