# Generated by Django 2.2.3 on 2019-08-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190806_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
        migrations.AddField(
            model_name='image',
            name='deskripsi_project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
