# Generated by Django 2.2.3 on 2019-07-23 00:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190714_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[blog.models.validate_image], verbose_name='Image'),
        ),
    ]
