# Generated by Django 2.2.3 on 2019-07-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerifoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeripost',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
