# Generated by Django 2.2.3 on 2019-07-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerifoto', '0002_galeripost_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeripost',
            old_name='description',
            new_name='title',
        ),
    ]
