# Generated by Django 2.2.3 on 2019-07-21 19:57

from django.db import migrations, models
import galerifoto.validators


class Migration(migrations.Migration):

    dependencies = [
        ('galerifoto', '0004_auto_20190721_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeripost',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[galerifoto.validators.validate_file_size]),
        ),
    ]
