# Generated by Django 2.2.3 on 2019-07-21 20:04

from django.db import migrations, models
import galerifoto.models


class Migration(migrations.Migration):

    dependencies = [
        ('galerifoto', '0006_auto_20190721_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeripost',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[galerifoto.models.validate_image], verbose_name='Image'),
        ),
    ]
