# Generated by Django 2.2.3 on 2019-08-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerifoto', '0008_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeripost',
            name='title',
        ),
        migrations.AddField(
            model_name='galeripost',
            name='nama_kegiatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
