# Generated by Django 2.2.3 on 2019-07-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bogrades_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
