# Generated by Django 2.2.3 on 2019-07-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('nama_lengkap', models.CharField(max_length=50)),
                ('tgl_lahir', models.DateField(verbose_name='Birthday')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.TextField()),
                ('no_hp', models.IntegerField()),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('id_instagram', models.CharField(max_length=50)),
                ('fb_url', models.URLField()),
                ('web_portofolio_url', models.URLField()),
                ('pekerjaan', models.CharField(choices=[('pljr/mhs', 'Pelajar/Mahasiswa'), ('freelance', 'Freelance'), ('karyawan', 'Karyawan'), ('blmbekerja', 'Belum Bekerja'), ('tgahli', 'Tenaga Ahli'), ('wiraswasta', 'Wiraswasta'), ('lain', 'Lain-lain')], max_length=15)),
                ('bidang_desain', models.CharField(choices=[('branding', 'Branding'), ('illustration', 'Illustration'), ('publication', 'Publication'), ('webdesign', 'Web Design'), ('photography', 'Photography'), ('infographic', 'Infographic'), ('mograph', 'Motion Graphic'), ('dgimaging', 'Digital Imaging'), ('typography', 'Typography'), ('wpap', 'WPAP'), ('lettering', 'Lettering'), ('doodle', 'Doodle'), ('mural', 'Mural'), ('drawing', 'drawing'), ('fashiondesign', 'Fashion Design'), ('lain', 'Lain-lain')], max_length=15)),
                ('program_desain', models.CharField(choices=[('manual', 'Manual'), ('ps', 'Adobe Photoshop'), ('ai', 'Adobe Illustrator'), ('id', 'Adobe Indesign'), ('corel', 'CorelDraw'), ('autocad', 'Autocad'), ('paint', 'Paint'), ('mangastudio', 'Manga Studio'), ('quark', 'Quark Xpress'), ('3ds', '3D Max'), ('ink', 'Inkscape'), ('sketchup', 'Google SketchUp'), ('macromedia', 'Macromedia Freehand'), ('lain', 'Lain-lain')], max_length=15)),
                ('deskripsi_diri', models.TextField()),
                ('tujuan_gabung_bogrades', models.TextField()),
                ('harapan_gabung_bogrades', models.TextField()),
                ('upload_foto_diri', models.ImageField(upload_to='photoprofile/')),
                ('upload_portofolio', models.ImageField(upload_to='portofolio/')),
            ],
        ),
    ]
